/**
 * matcher.mjs — 3-segment formula aware scoring for skill auto-suggest.
 *
 * Skill descriptions follow this pattern (generated by skill-reviewer):
 *   "<summary>. Use when: <triggers>. Key capabilities: <capabilities>."
 *
 * Score = weighted overlap of task words with the 3 segments:
 *   USE WHEN     (triggers)       → 1.0
 *   CAPABILITIES (what it does)   → 0.7
 *   KEY TASKS    (specific verbs) → 0.5
 *
 * Returns a normalized score in [0, 1].
 */

import { cosineSimilarity, normalizeSimilarity } from "./embedding.mjs";

/**
 * Common English stop words to exclude from keyword matching.
 */
const STOP_WORDS = new Set([
  "is", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "do", "does", "did", "will", "would", "could", "should",
  "to", "of", "in", "on", "at", "for", "with", "from", "by", "about",
  "and", "or", "but", "not", "no", "nor", "if", "then", "else",
  "a", "an", "the",
  "it", "its", "this", "that", "these", "those",
  "i", "you", "he", "she", "we", "they", "me", "him", "her", "us", "them",
  "my", "your", "his", "our", "their",
  "what", "which", "who", "whom", "whose", "where", "when", "why", "how",
]);

/**
 * Tokenize text for keyword matching.
 *   - ASCII alphanum sequences of 2+ chars become one token each.
 *   - Each CJK character becomes its own token.
 *   - Common English stop words are dropped.
 * This lets mixed Chinese/English tasks like "幫我寫封 email" match on "email",
 * and future Chinese skill descriptions match on individual hanzi.
 */
function tokenize(text) {
  if (!text || typeof text !== 'string') return [];
  const lower = text.toLowerCase();
  // ASCII word (2+) OR single CJK unified ideograph / hiragana / katakana / hangul
  const raw = lower.match(/[a-z0-9]{2,}|[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af]/g) || [];
  const tokens = raw.filter(t => t.length > 2 || !STOP_WORDS.has(t));
  return [...new Set(tokens)];
}

/**
 * Parse a skill description into 3 segments.
 * Default behavior: when no markers are found, treat the WHOLE description
 * as USE WHEN (most conservative — only "when to use" triggers score).
 */
export function parseSegments(description) {
  const segments = { useWhen: null, capabilities: null, keyTasks: null };
  if (!description || typeof description !== 'string') return segments;

  const text = description.trim();

  // Split on canonical 3-segment markers using a lookahead so abbreviations
  // like "e.g." / "i.e." inside a segment do not cause premature truncation.
  // Each segment runs until the next "<marker>:" or end of string.
  const useWhenMatch = text.match(/Use when:?\s*(.+?)(?=\.\s*(?:Key capabilities|Key tasks|Tasks):|$)/is);
  const capabilitiesMatch = text.match(/Key capabilities:?\s*(.+?)(?=\.\s*(?:Key tasks|Tasks):|$)/is);
  const keyTasksMatch = text.match(/(?:Key tasks|Tasks):?\s*(.+?)(?=\.\s*$|$)/is);

  if (useWhenMatch) segments.useWhen = useWhenMatch[1].trim();
  if (capabilitiesMatch) segments.capabilities = capabilitiesMatch[1].trim();
  if (keyTasksMatch) segments.keyTasks = keyTasksMatch[1].trim();

  // Default: if no USE WHEN segment found, treat whole description as USE WHEN.
  // This makes the matcher robust against hand-written or older skills.
  if (!segments.useWhen) segments.useWhen = text;

  return segments;
}

/**
 * Count how many task words appear in segmentText (overlap).
 */
function countOverlap(taskWords, segmentText) {
  if (!segmentText || taskWords.length === 0) return 0;
  const segmentWords = new Set(tokenize(segmentText));
  let overlap = 0;
  for (const w of taskWords) {
    if (segmentWords.has(w)) overlap++;
  }
  return overlap;
}

/**
 * Compute match score for one skill against a task string.
 *
 * @param {string} task        — the user task / message
 * @param {{description: string}} skill — skill with description field
 * @returns {number} — score in [0, 1]
 */
export function scoreSkill(task, skill) {
  if (!task || typeof task !== 'string' || !skill || !skill.description) return 0;

  const taskWords = tokenize(task);
  if (taskWords.length === 0) return 0;

  // For mixed CJK/ASCII tasks, only ASCII tokens (the ones that can match
  // English skill descriptions) are used for normalization. Pure-CJK tasks
  // fall back to all CJK tokens so future Chinese skills can still match.
  const asciiWords = taskWords.filter(w => /^[a-z0-9]+$/.test(w));
  const denominatorWords = asciiWords.length > 0 ? asciiWords : taskWords;

  const segments = parseSegments(skill.description);

  const useWhenScore     = countOverlap(taskWords, segments.useWhen);
  const capabilitiesScore = countOverlap(taskWords, segments.capabilities);
  const keyTasksScore    = countOverlap(taskWords, segments.keyTasks);

  // Weighted sum, normalized by max possible (all task words matching USE WHEN)
  const total = (useWhenScore * 1.0) + (capabilitiesScore * 0.7) + (keyTasksScore * 0.5);
  const maxPossible = denominatorWords.length * 1.0;

  return Math.min(total / maxPossible, 1.0);
}

/**
 * Compute vector similarity score for a task embedding against a skill embedding.
 *
 * @param {number[]} taskEmbedding
 * @param {number[]} skillEmbedding
 * @returns {number} — score in [0, 1]
 */
export function scoreSkillVector(taskEmbedding, skillEmbedding) {
  if (!taskEmbedding || !skillEmbedding) return 0;
  return normalizeSimilarity(cosineSimilarity(taskEmbedding, skillEmbedding));
}
