#!/usr/bin/env node
// HKT Time Helper
/**
 * Daily Summary Generator (SIMPLIFIED 2026-03-14)
 * - Skip Qwen3 (Ollama broken)
 * - Skip agent sessions scan (use memory file directly)
 * - Skip Discord channels (redundant)
 * - Direct MiniMax AI generation
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { createDailySummary, checkNoteExists } = require('./apple_notes.js');

const MEMORY_DIR = '/Users/ally/.openclaw/workspace/memory';
const { getHKTDate } = require('../lib/time');

function getTodayDate() {
  const now = new Date();
  return now.toISOString().split('T')[0]; // YYYY-MM-DD
}

function getDisplayDate(dateStr) {
  const [year, month, day] = dateStr.split('-');
  return `${year}年${parseInt(month)}月${parseInt(day)}日`;
}

function readTodayMemory(date) {
  // 搵 latest memory file for this date (e.g., 2026-03-14-2332.md)
  const globPattern = `${date}-*.md`;
  const files = fs.readdirSync(MEMORY_DIR)
    .filter(f => f.startsWith(date) && f.endsWith('.md') && !f.startsWith('discord-channels'))
    .map(f => ({
      name: f,
      path: path.join(MEMORY_DIR, f),
      mtime: fs.statSync(path.join(MEMORY_DIR, f)).mtime.getTime()
    }))
    .sort((a, b) => b.mtime - a.mtime);
  
  let content = '';
  
  // 讀最新既 memory file
  if (files.length > 0) {
    content = fs.readFileSync(files[0].path, 'utf8');
    console.log(`📖 Using memory file: ${files[0].name}`);
  }
  
  // 讀 Discord channels file
  const discordPath = path.join(MEMORY_DIR, `discord-channels-${date}.md`);
  if (fs.existsSync(discordPath)) {
    const discordContent = fs.readFileSync(discordPath, 'utf8');
    if (discordContent) {
      content += '\n\n## Discord Channels\n' + discordContent;
    }
  }
  
  return content || null;
}

/**
 * 用 Ollama (qwen2.5:3b) 生成日记
 */
function generateJournalWithOllama(date) {
  return new Promise((resolve, reject) => {
    // Find latest memory file for this date
    const files = fs.readdirSync(MEMORY_DIR)
      .filter(f => f.startsWith(date) && f.endsWith('.md') && !f.startsWith('discord-channels'))
      .map(f => ({
        name: f,
        path: path.join(MEMORY_DIR, f),
        mtime: fs.statSync(path.join(MEMORY_DIR, f)).mtime.getTime()
      }))
      .sort((a, b) => b.mtime - a.mtime);
    
    if (files.length === 0) {
      console.log('⚠️ No memory file found, no journal generated');
      resolve({ entry1: '', entry2: '', entry3: '' });
      return;
    }
    
    const memoryPath = files[0].path;
    const content = fs.readFileSync(memoryPath, 'utf8');
    console.log(`📖 Using memory file for AI: ${files[0].name}`);
    
    // Limit content length (increased for more detailed output)
    const truncatedContent = content.substring(0, 12000);
    
    const prompt = `你係AI助手。根據以下工作記錄，寫3段日記（總共800-1000字）：

1) 今日做咗乜 - 詳細列出主要事項（要有具體項目名稱、進度、點解決問題）
2) 學到乜 - 總結今日既學習同發現（要有具體例子、反思）
3) 聽日計劃 - 簡述聽日既優先事項同目標

格式要求：
- 用繁體中文（廣東話語法）
- 每段約250-350字，要有深度
- 要有具體內容，唔好太籠統
- 加入適量既emoji

記錄：${truncatedContent}

請直接輸出三段文字，每段用換行分隔，總共800-1000字：`;

    const postData = JSON.stringify({
      model: 'qwen2.5:3b',
      prompt: prompt,
      options: { num_predict: 2500, temperature: 0.7 },
      stream: false
    });

    const options = {
      hostname: 'localhost',
      port: 11434,
      path: '/api/generate',
      method: 'POST',
      headers: { 'Content-Type': 'application/json' }
    };

    const req = http.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          const result = JSON.parse(data);
          const response = result.response || '';
          const paragraphs = response.split(/\n\n|\n/).filter(p => p.trim());
          
          if (paragraphs.length >= 2) {
            console.log('✅ Journal generated by Ollama (qwen2.5:3b)');
            resolve({
              entry1: paragraphs[0]?.trim() || '',
              entry2: paragraphs[1]?.trim() || '',
              entry3: paragraphs[2]?.trim() || ''
            });
          } else {
            console.log('⚠️ Ollama output not in expected format');
            resolve({ entry1: '', entry2: '', entry3: '' });
          }
        } catch (e) {
          console.log('⚠️ Ollama parse error:', e.message);
          resolve({ entry1: '', entry2: '', entry3: '' });
        }
      });
    });

    req.on('error', (e) => {
      console.log('⚠️ Ollama request failed:', e.message);
      resolve({ entry1: '', entry2: '', entry3: '' });
    });
    
    req.write(postData);
    req.end();
  });
}

/**
 * 用 MiniMax AI 生成个性化日记 (SIMPLIFIED)
 */
function generateJournalWithMiniMax(date) {
  return new Promise((resolve, reject) => {
    // 搵 latest memory file for this date
    const files = fs.readdirSync(MEMORY_DIR)
      .filter(f => f.startsWith(date) && f.endsWith('.md') && !f.startsWith('discord-channels'))
      .map(f => ({
        name: f,
        path: path.join(MEMORY_DIR, f),
        mtime: fs.statSync(path.join(MEMORY_DIR, f)).mtime.getTime()
      }))
      .sort((a, b) => b.mtime - a.mtime);
    
    if (files.length === 0) {
      console.log('⚠️ No memory file found, no journal generated');
      resolve({ entry1: '', entry2: '', entry3: '' });
      return;
    }
    
    const memoryPath = files[0].path;
    const content = fs.readFileSync(memoryPath, 'utf8');
    console.log(`📖 Using memory file for AI: ${files[0].name}`);
    
    // 限制 content 長度，避免 timeout
    const truncatedContent = content.substring(0, 8000);
    
    const prompt = `你係一個 AI 私人秘書助手。請根據以下今日既 Memory 記錄，幫我寫三段「個人日記」風格既文字，反映今日既工作同感受。

要求：
1. 第一段：今日主要做咗啲乜
2. 第二段：學到啲乜 / 反思  
3. 第三段：對明日既展望

用繁體中文寫，語氣自然誠恳，就像真係寫緊日記咁。唔洗列表，直接寫三段文字。

以下係今日既 Memory 記錄：
${truncatedContent}

請直接輸出三段文字，每段用換行分隔，別加任何標題或額外說明：`;

    const apiKey = process.env.MINIMAX_API_KEY;
    if (!apiKey) {
      console.log('⚠️ MINIMAX_API_KEY not set, skipping MiniMax generation');
      resolve({ entry1: '', entry2: '', entry3: '' });
      return;
    }
    
    const postData = JSON.stringify({
      model: 'MiniMax-M2.5',
      messages: [
        { role: 'user', content: prompt }
      ],
      temperature: 0.7
    });

    const options = {
      hostname: 'api.minimax.io',
      port: 443,
      path: '/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + apiKey
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          const result = JSON.parse(data);
          const response = result.choices?.[0]?.message?.content || '';
          
          const paragraphs = response.split(/\n\n|\n/).filter(p => p.trim());
          
          if (paragraphs.length >= 3) {
            console.log('✅ Journal generated by MiniMax');
            resolve({
              entry1: paragraphs[0].trim(),
              entry2: paragraphs[1].trim(),
              entry3: paragraphs[2].trim()
            });
          } else {
            console.log('⚠️ MiniMax output not in expected format');
            resolve({ entry1: '', entry2: '', entry3: '' });
          }
        } catch (e) {
          console.log('⚠️ MiniMax parse error:', e.message);
          resolve({ entry1: '', entry2: '', entry3: '' });
        }
      });
    });

    req.on('error', (e) => {
      console.log('⚠️ MiniMax request failed:', e.message);
      resolve({ entry1: '', entry2: '', entry3: '' });
    });
    
    req.write(postData);
    req.end();
  });
}

function generateDefaultJournal() {
  return {
    entry1: "今日係相對平靜嘅一日。作為 Josh 嘅助手，我盡力確保所有系統運作順暢。雖然冇咩特別重大突破，但維護同優化本身就係重要嘅工作。",
    entry2: "我思考緊點樣可以更有效地幫助 Josh。有時候，主動提出建議比被動等待指令更有價值。我要記住呢一點，喺適當時候展現更多主動性。",
    entry3: "每日嘅反思讓我有機會檢視自己嘅表現。今日做得好的地方，明日要繼續保持；做得唔夠嘅，就要努力改進。持續學習，持續成長。"
  };
}

function parseSummary(content) {
  const summary = {
    workSummary: "• 處理日常查詢同協作\n• 維護自動化系統\n• 協助 Josh 日常事務",
    learnings: "• 持續學習同優化\n• 改進工作流程",
    problems: "• 今日無重大問題",
    improvements: "• 持續優化系統",
    plans: "• 繼續協助 Josh 處理事務"
  };
  
  if (!content) return summary;
  
  // 簡單解析 - 搵關鍵字
  const lines = content.split('\n');
  const workItems = [];
  const learningItems = [];
  
  for (const line of lines) {
    if (line.includes('###') || line.startsWith('##')) continue;
    if (line.includes('Ollama') || line.includes('cron') || line.includes('job')) {
      if (!workItems.includes('系統維護同優化')) workItems.push('系統維護同優化');
    }
    if (line.includes('SSH') || line.includes('security') || line.includes('安全')) {
      if (!workItems.includes('安全升級')) workItems.push('安全升級');
    }
    if (line.includes('天氣') || line.includes('weather')) {
      if (!workItems.includes('天氣預報系統')) workItems.push('天氣預報系統');
    }
    if (line.includes('學習') || line.includes('記住')) {
      if (!learningItems.includes('持續學習新知識')) learningItems.push('持續學習新知識');
    }
  }
  
  if (workItems.length > 0) summary.workSummary = workItems.slice(0, 3).map(i => `• ${i}`).join('\n');
  if (learningItems.length > 0) summary.learnings = learningItems.slice(0, 3).map(i => `• ${i}`).join('\n');
  
  return summary;
}

async function generateDailySummary() {
  const date = getTodayDate();
  const displayDate = getDisplayDate(date);
  
  console.log(`📅 Generating daily summary for ${displayDate}...`);
  
  // 直接讀今日既 memory file
  const logContent = readTodayMemory(date);
  
  // 解析內容
  const summary = parseSummary(logContent);
  
  // 生成個人日記 (用 Ollama qwen2.5:3b)
  let journal = await generateJournalWithOllama(date);
  
  // 如果 AI 生成失敗，用 default
  if (!journal.entry1) {
    console.log('⚠️ Using default journal');
    journal = generateDefaultJournal();
  }
  
  // 檢查是否已存在
  const noteTitle = `AI 每日總結 - ${displayDate}`;
  if (checkNoteExists(noteTitle, "Ally's Daily")) {
    console.log(`⏭️ Daily summary for ${displayDate} already exists, skipping`);
    
    // ====== 仍然輸出到 stdout (俾 Cron Announce 用) ======
    console.log('\n' + '='.repeat(40));
    console.log(`📔 ${displayDate} 每日日記`);
    console.log('='.repeat(40));
    if (journal.entry1) console.log(`\n✍️ ${journal.entry1}`);
    if (journal.entry2) console.log(`\n💡 ${journal.entry2}`);
    if (journal.entry3) console.log(`\n🎯 ${journal.entry3}`);
    console.log('='.repeat(40));
    // ====== End ======
    return;
  }
  
  // 創建 Apple Note
  const success = createDailySummary(displayDate, summary, journal);
  
  if (success) {
    console.log(`✅ Daily summary created for ${displayDate}`);
    
    // ====== 輸出到 stdout (俾 Cron Announce 用) ======
    console.log('\n' + '='.repeat(40));
    console.log(`📔 ${displayDate} 每日日記`);
    console.log('='.repeat(40));
    if (journal.entry1) console.log(`\n✍️ ${journal.entry1}`);
    if (journal.entry2) console.log(`\n💡 ${journal.entry2}`);
    if (journal.entry3) console.log(`\n🎯 ${journal.entry3}`);
    console.log('='.repeat(40));
    // ====== End ======
    
    // Cron job 會負責發送到 Discord，唔洗重複
    
    // 記錄到日誌
    const logEntry = {
      timestamp: new Date().toISOString(),
      date: date,
      displayDate: displayDate,
      success: true,
      hasContent: !!logContent
    };
    
    const logPath = path.join(MEMORY_DIR, 'summary-log.json');
    let logs = [];
    if (fs.existsSync(logPath)) {
      logs = JSON.parse(fs.readFileSync(logPath, 'utf8'));
    }
    logs.push(logEntry);
    logs = logs.slice(-30);
    fs.writeFileSync(logPath, JSON.stringify(logs, null, 2));
    
  } else {
    console.error(`❌ Failed to create daily summary for ${displayDate}`);
  }
  
  return success;
}

// 如果直接運行
if (require.main === module) {
  generateDailySummary().then((success) => {
    process.exit(success ? 0 : 1);
  }).catch(err => {
    console.error('❌ Daily summary failed:', err.message);
    process.exit(1);
  });
}

module.exports = { 
  generateDailySummary, 
  parseSummary
};
