// scripts/lib/safe_fs.js — Auto-generated by observe_audit_patterns.js
// Pattern: fsSync_missing_trycatch (55 occurrences across 1 days)
// Purpose: Provide safe wrappers for fs.*Sync functions that catch exceptions
//          and return null/error instead of throwing.
//
// Usage:
//   const safeFs = require('./lib/safe_fs');
//   safeFs.writeFileSync('/path/to/file', content);  // returns true|false
//
// Migration: replace fs.writeFileSync(path, data) with safeFs.writeFileSync(path, data)
'use strict';
const fs = require('fs');
const path = require('path');

function writeFileSync(filePath, data, options) {
  try {
    fs.writeFileSync(filePath, data, options);
    return true;
  } catch (e) {
    console.error('[safe_fs] writeFileSync failed:', filePath, e.message);
    return false;
  }
}

function readFileSync(filePath, options) {
  try {
    return fs.readFileSync(filePath, options);  // returns string/Buffer, matches fs.readFileSync API
  } catch (e) {
    console.error('[safe_fs] readFileSync failed:', filePath, e.message);
    return null;  // explicit null on failure (callers should null-check)
  }
}

function appendFileSync(filePath, data, options) {
  try {
    fs.appendFileSync(filePath, data, options);
    return true;
  } catch (e) {
    console.error('[safe_fs] appendFileSync failed:', filePath, e.message);
    return false;
  }
}

module.exports = { writeFileSync, readFileSync, appendFileSync };
