/**
 * whitelist_patterns.js - False Positive Whitelist
 * AUTO-GENERATED by PatternLearner
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2026-05-06T02:04:34.228Z
 * File:Line patterns: 3
 * Semantic patterns: 9
 */

module.exports = {
  VERSION: '1.0.0',
  generatedAt: '2026-05-06T02:04:34.228Z',

  // ==================== File:Line Patterns ====================
  // False Positive patterns (regex strings)
  // Each pattern is a string that will be used to match against
  // {file}:{line}:{rule} format
  patterns: [
  "scripts/analyze_magic_numbers.js:L39:magic_numbers:Hardcoded_magic_number",
  "scripts/analyze_magic_numbers.js:L40:magic_numbers:Hardcoded_magic_number",
  "scripts/analyze_magic_numbers.js:L41:magic_numbers:Hardcoded_magic_number"
],

  // Pattern details (for debugging)
  details: [
  {
    "id": "fp_magic_numbers_1777576248551",
    "pattern_key": "scripts/analyze_magic_numbers.js:39:magic_numbers",
    "pattern": "scripts/analyze_magic_numbers.js:L39:magic_numbers:Hardcoded_magic_number",
    "rule": "magic_numbers",
    "learned_at": "2026-04-30",
    "last_seen": "2026-04-30",
    "confidence": 100,
    "count": 11,
    "source": "local",
    "examples": [
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的已知端口\n。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index \n1，此數字為 `ollamaPorts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字\n為 `ollamaPorts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaP\norts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名\n單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的\n已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的已知端口\n。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 39,
        "reasoning": "同 index 1，此數字為 `ollamaPorts` 白名單正則中的已知端口。",
        "learned_at": "2026-04-30"
      }
    ]
  },
  {
    "id": "fp_magic_numbers_1777576248552",
    "pattern_key": "scripts/analyze_magic_numbers.js:40:magic_numbers",
    "pattern": "scripts/analyze_magic_numbers.js:L40:magic_numbers:Hardcoded_magic_number",
    "rule": "magic_numbers",
    "learned_at": "2026-04-30",
    "last_seen": "2026-04-30",
    "confidence": 100,
    "count": 2,
    "source": "local",
    "examples": [
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 40,
        "reasoning": "此數字\n為 `memorySize` 白名單正則的一部分，用於標記常見的 token 記憶體大小（如 4K token\ns）。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 40,
        "reasoning": "同 index 13，此數字為 `memorySize` 白名單正則中的已知記憶體大小（8\nK tokens）。",
        "learned_at": "2026-04-30"
      }
    ]
  },
  {
    "id": "fp_magic_numbers_1777576248552",
    "pattern_key": "scripts/analyze_magic_numbers.js:41:magic_numbers",
    "pattern": "scripts/analyze_magic_numbers.js:L41:magic_numbers:Hardcoded_magic_number",
    "rule": "magic_numbers",
    "learned_at": "2026-04-30",
    "last_seen": "2026-04-30",
    "confidence": 100,
    "count": 2,
    "source": "local",
    "examples": [
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 41,
        "reasoning": "此數字為 `pdfMagic` 白名單正則中的 PDF/GIF 檔案魔術位元組\n（Magic Bytes），是檔案格式識別的標準常量。",
        "learned_at": "2026-04-30"
      },
      {
        "file": "scripts/analyze_magic_numbers.js",
        "line": 41,
        "reasoning": "同 index 15，此數字為 GIF\n檔案的魔術位元組（47494638 = \\'GIF8\\'），屬於標準檔案簽名。",
        "learned_at": "2026-04-30"
      }
    ]
  }
],

  // ==================== Semantic Patterns (Phase 2) ====================
  // Cross-file semantic patterns for automatic FP detection
  semanticPatterns: [
  {
    "name": "comment_date_year",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "(20\\d{2})",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "comment",
    "explanation": "Year numbers (20xx) in comments are documentation dates"
  },
  {
    "name": "comment_fix_date",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "20\\d{2}-\\d{2}-\\d{2}",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "comment",
    "explanation": "Date in fix annotation like (修復 2026-04-04)"
  },
  {
    "name": "comment_line_ref",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "\\d{3,5}",
    "fullPattern": "(原\\s*Lines?|Lines?)\\s*[~-]?\\s*\\d{3,5}",
    "lookbehind": null,
    "lookahead": null,
    "context": "comment",
    "explanation": "Numbers in line reference comments like 原 Lines 1100-1600"
  },
  {
    "name": "standard_timeout_ms",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "\\b(5000|10000|15000|30000|60000)\\b",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "code",
    "explanation": "Standard timeout values in milliseconds (5s, 10s, 15s, 30s, 60s)"
  },
  {
    "name": "ecmascript_version",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "ecma(?:ma)?Version.*\\d{4}",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "code",
    "explanation": "ECMAScript version numbers in parser configuration"
  },
  {
    "name": "byte_conversion_factor",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "\\b(1024|2048|4096|8192|65536)\\b",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "code",
    "explanation": "Standard byte conversion factors (powers of 2)"
  },
  {
    "name": "discord_snowflake",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "\\b1[4-5]\\d{16,19}\\b",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "code",
    "explanation": "Discord snowflake IDs (17-20 digits starting with 14-15)"
  },
  {
    "name": "file_size_config",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "\\b(100000|500000|1000000)\\b",
    "fullPattern": null,
    "lookbehind": null,
    "lookahead": null,
    "context": "code",
    "explanation": "File size configuration constants"
  },
  {
    "name": "comment_line_ref_magic_numbers",
    "type": "semantic",
    "rule": "magic_numbers",
    "pattern": "(\\d{3,5})",
    "fullPattern": null,
    "lookbehind": "原\\s*Lines?|Lines?",
    "lookahead": null,
    "context": "comment",
    "explanation": "Numbers in line reference comments are code references, not values"
  }
],

  // Semantic pattern count
  semanticCount: 9,

  // Total count
  count: 12
};

// ==================== Semantic Pattern Matching Functions ====================
// Phase 2: Semantic Pattern Learning for cross-file FP detection

/**
 * isFalsePositive - 檢查 issue 是否為 false positive
 * 支援 file:line 匹配和 semantic pattern 匹配
 *
 * @param {Object} issue - { file, line, rule, code, lineContent }
 * @param {Object} options - { useSemantic: true/false }
 * @returns {Object} - { isFP, reason, matchedPattern, method }
 */
function isFalsePositive(issue, options = {}) {
  const { useSemantic = true } = options;

  // 1. 檢查 file:line whitelist
  if (isFileLineWhitelisted(issue)) {
    return { isFP: true, reason: 'matched_file_line_pattern', method: 'file:line' };
  }

  // 2. 檢查 semantic patterns
  if (useSemantic) {
    const semanticMatch = matchSemanticPattern(issue);
    if (semanticMatch.matched) {
      return {
        isFP: true,
        reason: semanticMatch.pattern.explanation,
        matchedPattern: semanticMatch.pattern.name,
        method: 'semantic'
      };
    }
  }

  return { isFP: false };
}

/**
 * isFileLineWhitelisted - 檢查 file:line 是否在白名單
 */
function isFileLineWhitelisted(issue) {
  const whitelist = module.exports.patterns;
  const pattern = issue.file + ':L' + issue.line + ':' + issue.rule;

  return whitelist.some(p => {
    // 精確匹配
    if (p === pattern) return true;
    // 帶關鍵詞匹配
    if (p.includes(issue.file + ':L' + issue.line + ':')) return true;
    return false;
  });
}

/**
 * matchSemanticPattern - 匹配 semantic pattern
 */
function matchSemanticPattern(issue) {
  const semanticPatterns = module.exports.semanticPatterns || [];

  if (!semanticPatterns || semanticPatterns.length === 0) {
    return { matched: false };
  }

  const lineContent = issue.code || issue.lineContent || '';
  const rule = issue.rule;

  for (const sp of semanticPatterns) {
    // 檢查 rule 匹配
    if (sp.rule && sp.rule !== rule) continue;

    // 根據 context 匹配
    if (sp.context === 'comment') {
      if (!isCommentLine(lineContent)) continue;
      if (matchSemantic(sp, lineContent)) {
        return { matched: true, pattern: sp };
      }
    } else if (sp.context === 'code') {
      if (isCommentLine(lineContent)) continue;
      if (matchSemantic(sp, lineContent)) {
        return { matched: true, pattern: sp };
      }
    } else {
      // any context
      if (matchSemantic(sp, lineContent)) {
        return { matched: true, pattern: sp };
      }
    }
  }

  return { matched: false };
}

/**
 * isCommentLine - 檢查是否為註釋行
 */
function isCommentLine(lineContent) {
  const trimmed = lineContent.trim();
  return (
    trimmed.startsWith('//') ||
    trimmed.startsWith('/*') ||
    trimmed.startsWith('*') ||
    trimmed.startsWith('#')
  );
}

/**
 * matchSemantic - 匹配 semantic pattern
 */
function matchSemantic(sp, content) {
  // 如果有 fullPattern，直接使用
  if (sp.fullPattern) {
    try {
      const regex = new RegExp(sp.fullPattern, 'g');
      return regex.test(content);
    } catch {
      return false;
    }
  }

  // 否則使用 pattern + lookbehind/lookahead
  try {
    let fullPattern = sp.pattern || '';
    if (sp.lookbehind) {
      fullPattern = '(?<=' + sp.lookbehind + ')' + fullPattern;
    }
    if (sp.lookahead) {
      fullPattern = fullPattern + '(?=' + sp.lookahead + ')';
    }
    const regex = new RegExp(fullPattern, 'g');
    return regex.test(content);
  } catch {
    return false;
  }
}

/**
 * filterFalsePositives - 批量過濾 false positives
 *
 * @param {Array} issues - Issues 據組
 * @param {Object} options - { useSemantic: true }
 * @returns {Object} - { falsePositives: [], truePositives: [] }
 */
function filterFalsePositives(issues, options = {}) {
  const falsePositives = [];
  const truePositives = [];

  for (const issue of issues) {
    const result = isFalsePositive(issue, options);
    if (result.isFP) {
      falsePositives.push({ issue, ...result });
    } else {
      truePositives.push(issue);
    }
  }

  return { falsePositives, truePositives };
}

// Export matching functions
module.exports.isFalsePositive = isFalsePositive;
module.exports.isFileLineWhitelisted = isFileLineWhitelisted;
module.exports.matchSemanticPattern = matchSemanticPattern;
module.exports.filterFalsePositives = filterFalsePositives;
module.exports.isCommentLine = isCommentLine;
