#!/usr/bin/env node
/**
 * observe_audit_patterns.js — Layer 4 v0: Audit Pattern Observer + Wrapper Generator
 *
 * Reads .state/audit_history/audit_*.json (Layer 3 output), identifies recurring
 * fix patterns across days, and generates safe-wrapper templates for the top
 * offenders. The wrappers are template-only (no auto-migration) — v1 will
 * actually rewrite files.
 *
 * Phase 2 architecture:
 *   Layer 1 — edit-verify (LOW_RISK fix, syntax)
 *   Layer 2 — cross-script propagation (rename, signature)
 *   Layer 3 — script registry + daily audit (this script reads Layer 3 output)
 *   Layer 4 — predictive hardening (this script generates safe wrappers)
 *
 * Tier 2 / D v0 (2026-06-20): observation + wrapper template generation.
 * Tier 2 / D v1 (future): auto-migrate scripts to use the wrappers.
 *
 * Output:
 *   - .analysis/audit_patterns_<date>.md          (human-readable report)
 *   - .analysis/audit_patterns_<date>.json        (machine-readable)
 *   - scripts/lib/safe_<rule>.js                  (wrapper template, only if --generate)
 *
 * Usage:
 *   node scripts/observe_audit_patterns.js                  # observe + report
 *   node scripts/observe_audit_patterns.js --generate        # + write wrapper templates
 *   node scripts/observe_audit_patterns.js --days 7          # custom window
 *   node scripts/observe_audit_patterns.js --threshold 5     # only rules with ≥5 occurrences
 *   node scripts/observe_audit_patterns.js --dry-run         # preview, no writes
 */
'use strict';

const fs = require('fs');
const path = require('path');

const { WS, STATE_DIR } = require('./lib/config');

const AUDIT_HISTORY_DIR = path.join(STATE_DIR, 'audit_history');
const ANALYSIS_DIR = path.join(WS, '.analysis');
const LIB_DIR = path.join(WS, 'scripts', 'lib');

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const GENERATE = args.includes('--generate');
const daysIdx = args.indexOf('--days');
const DAYS = daysIdx >= 0 ? parseInt(args[daysIdx + 1], 10) || 7 : 7;
const thrIdx = args.indexOf('--threshold');
const THRESHOLD = thrIdx >= 0 ? parseInt(args[thrIdx + 1], 10) || 3 : 3;

function log(msg) { console.log(msg); }
function err(msg) { console.error(msg); }

function loadAuditHistory(days) {
  if (!fs.existsSync(AUDIT_HISTORY_DIR)) return [];
  const cutoff = Date.now() - days * 24 * 60 * 60 * 1000;
  let files = [];
  try {
    files = fs.readdirSync(AUDIT_HISTORY_DIR);
  } catch (e) {
    // FIX (2026-06-21): previous code called .filter() on undefined when
    // readdirSync threw, which made the script crash silently with TypeError.
    // Return [] so the caller can degrade gracefully ("no history available").
    console.error(`Operation failed: ${e.message}`);
    return [];
  }
  files = files
    .filter(f => f.startsWith('audit_') && f.endsWith('.json'))
    .sort();
  const all = [];
  for (const f of files) {
    const path = `${AUDIT_HISTORY_DIR}/${f}`;
    let data;
    try { data = JSON.parse(fs.readFileSync(path, 'utf8')); } catch (e) { continue; }
    const date = f.match(/audit_(\d{4}-\d{2}-\d{2})\.json/)?.[1];
    if (!date) continue;
    // Check file age
    const fileMtime = fs.statSync(path).mtimeMs;
    if (fileMtime < cutoff) continue;
    const issues = (data.results && data?.results?.merged) || [];
    for (const issue of issues) {
      all.push({ date, ...issue });
    }
  }
  return all;
}

function aggregateByRule(issues) {
  const byRule = {};
  for (const i of issues) {
    const r = i.rule || 'unknown';
    if (!byRule[r]) byRule[r] = { count: 0, dates: new Set(), files: new Set(), samples: [] };
    byRule[r].count++;
    byRule[r].dates.add(i.date);
    byRule[r].files.add(i.file);
    if (byRule[r].samples.length < 5) byRule[r].samples.push({ file: i.file, line: i.line });
  }
  // Convert Sets to sizes
  for (const r of Object.keys(byRule)) {
    byRule[r].dateCount = byRule[r].dates.size;
    byRule[r].fileCount = byRule[r].files.size;
    byRule[r].dates = [...byRule[r].dates];
    byRule[r].files = [...byRule[r].files].slice(0, 5); // top 5
  }
  return byRule;
}

// ── Wrapper templates (Layer 4 v0) ─────────────────────────────────────────
// For each known recurring pattern, generate a safe wrapper template.
// v0: just the template file. v1 will auto-migrate scripts to use it.

const WRAPPER_TEMPLATES = {
  'fsSync_missing_trycatch': (rule, info) => `// scripts/lib/safe_fs.js — Auto-generated by observe_audit_patterns.js
// Pattern: ${rule} (${info.count} occurrences across ${info.dateCount} days)
// Purpose: Provide safe wrappers for fs.*Sync functions that catch exceptions
//          and return null/error instead of throwing.
//
// Usage:
//   const safeFs = require('./lib/safe_fs');
//   safeFs.writeFileSync('/path/to/file', content);  // returns true|false
//
// Migration: replace fs.writeFileSync(path, data) with safeFs.writeFileSync(path, data)
'use strict';
const fs = require('fs');
const path = require('path');

function writeFileSync(filePath, data, options) {
  try {
    fs.writeFileSync(filePath, data, options);
    return true;
  } catch (e) {
    console.error('[safe_fs] writeFileSync failed:', filePath, e.message);
    return false;
  }
}

function readFileSync(filePath, options) {
  try {
    return { ok: true, data: fs.readFileSync(filePath, options) };
  } catch (e) {
    console.error('[safe_fs] readFileSync failed:', filePath, e.message);
    return { ok: false, error: e.message };
  }
}

function appendFileSync(filePath, data, options) {
  try {
    fs.appendFileSync(filePath, data, options);
    return true;
  } catch (e) {
    console.error('[safe_fs] appendFileSync failed:', filePath, e.message);
    return false;
  }
}

module.exports = { writeFileSync, readFileSync, appendFileSync };
`,

  'hardcoded-home-path': (rule, info) => `// scripts/lib/path_resolver.js — Auto-generated by observe_audit_patterns.js
// Pattern: ${rule} (${info.count} occurrences across ${info.dateCount} days)
// Purpose: Resolve hardcoded /Users/ally/... paths to workspace-relative or
//          OS-portable paths.
//
// Usage:
//   const pathResolver = require('./lib/path_resolver');
//   pathResolver.resolve('/Users/ally/.openclaw/workspace/scripts/foo.js');
//
'use strict';
const path = require('path');
const os = require('os');

const HOME = os.homedir();
const WS = path.join(HOME, '.openclaw', 'workspace');

function resolve(p) {
  if (!p) return p;
  if (p.startsWith('~/')) return path.join(HOME, p.slice(2));
  if (p.startsWith('$HOME/') || p.startsWith(HOME)) {
    return p.replace(HOME, '~');
  }
  return p;
}

module.exports = { resolve, HOME, WS };
`,

  'simplified-chinese': (rule, info) => `// scripts/lib/cjk_filter.js — Auto-generated by observe_audit_patterns.js
// Pattern: ${rule} (${info.count} occurrences across ${info.dateCount} days)
// Purpose: Filter out 簡體 (Simplified Chinese) characters, replacing with
//          繁體 (Traditional) equivalents. Useful for Cantonese-first systems.
//
// Usage:
//   const cjkFilter = require('./lib/cjk_filter');
//   cjkFilter.toTraditional('简體字');  // returns '繁體字'
//
'use strict';

// Minimal hand-curated table (expand as needed).
const SIMP_TO_TRAD = {
  '简': '簡', '體': '體', '国': '國', '语': '語',
  '業': '業', '學': '學', '習': '習', '說': '說',
  '為': '為', '時': '時', '間': '間', '应': '應',
  '對': '對', '會': '會', '發': '發', '開': '開',
  '關': '關', '审': '審', '計': '計', '理': '理',
};

function toTraditional(s) {
  if (!s) return s;
  let out = '';
  for (const ch of s) {
    out += SIMP_TO_TRAD[ch] || ch;
  }
  return out;
}

function hasSimplified(s) {
  if (!s) return false;
  for (const ch of s) {
    if (SIMP_TO_TRAD[ch]) return true;
  }
  return false;
}

module.exports = { toTraditional, hasSimplified };
`,
};

function generateWrapperTemplate(rule, info) {
  return WRAPPER_TEMPLATES[rule] && WRAPPER_TEMPLATES[rule](rule, info);
}

// Map audit rule names to natural module filenames.
// A rule may be tied to multiple audit issues (e.g., fsSync_missing_trycatch covers
// writeFileSync, readFileSync, appendFileSync), so a single wrapper addresses them all.
const RULE_TO_FILENAME = {
  'fsSync_missing_trycatch': 'safe_fs',
  'hardcoded-home-path': 'path_resolver',
  'simplified-chinese': 'cjk_filter',
};

function safeWrapperFilename(rule) {
  return (RULE_TO_FILENAME[rule] || ('safe_' + rule)) + '.js';
}

// ── Output writers ────────────────────────────────────────────────────────

function writeJsonReport(rules, dateStr) {
  const file = path.join(ANALYSIS_DIR, `audit_patterns_${dateStr}.json`);
  try {
    if (!fs.existsSync(ANALYSIS_DIR)) fs.mkdirSync(ANALYSIS_DIR, { recursive: true });
  } catch (e) {
    console.error(`Directory creation failed: ${e.message}`);
  }
  const report = {
    auditDate: new Date().toISOString(),
    windowDays: DAYS,
    threshold: THRESHOLD,
    totalIssues: rules.reduce((s, r) => s + r.count, 0),
    uniqueRules: rules.length,
    recurringRules: rules.filter(r => r.count >= THRESHOLD).length,
    rules: rules.sort((a, b) => b.count - a.count),
  };
  try {
    fs.writeFileSync(file, JSON.stringify(report, null, 2), 'utf8');
  } catch (e) {
    console.error(`File write failed: ${e.message}`);
  }
  return file;
}

function writeMdReport(rules, dateStr) {
  const file = path.join(ANALYSIS_DIR, `audit_patterns_${dateStr}.md`);
  try {
    if (!fs.existsSync(ANALYSIS_DIR)) fs.mkdirSync(ANALYSIS_DIR, { recursive: true });
  } catch (e) {
    console.error(`Directory creation failed: ${e.message}`);
  }
  const lines = [];
  lines.push(`# Audit Patterns — ${dateStr} (Layer 4 v0)`);
  lines.push('');
  lines.push(`> Window: ${DAYS} days · Threshold: ${THRESHOLD} occurrences`);
  lines.push(`> Total issues: ${rules.reduce((s, r) => s + r.count, 0)} · Unique rules: ${rules.length}`);
  lines.push('');
  lines.push('## Recurring Patterns (≥ threshold)');
  lines.push('');
  lines.push('| Rule | Occurrences | Days | Files | Wrapper |');
  lines.push('|------|-------------|------|-------|---------|');
  const recurring = rules.filter(r => r.count >= THRESHOLD);
  for (const r of recurring) {
    const hasWrapper = WRAPPER_TEMPLATES[r.rule] ? '✓' : '—';
    lines.push(`| \`${r.rule}\` | ${r.count} | ${r.dateCount} | ${r.fileCount} | ${hasWrapper} |`);
  }
  lines.push('');
  lines.push('## Suggested Actions');
  lines.push('');
  for (const r of recurring) {
    if (WRAPPER_TEMPLATES[r.rule]) {
      lines.push(`### ${r.rule}`);
      lines.push(`- **${r.count} occurrences** across ${r.dateCount} days`);
      lines.push(`- **${r.fileCount} unique files** affected`);
      lines.push(`- **Suggested wrapper**: \`scripts/lib/${safeWrapperFilename(r.rule)}\``);
      lines.push(`- Run with \`--generate\` flag to write wrapper template.`);
      lines.push('');
    } else {
      lines.push(`### ${r.rule}`);
      lines.push(`- **${r.count} occurrences** — no wrapper template yet, consider manual fix.`);
      lines.push('');
    }
  }
  try {
    fs.writeFileSync(file, lines.join('\n'), 'utf8');
  } catch (e) {
    console.error(`File write failed: ${e.message}`);
  }
  return file;
}

function writeWrapperTemplates(rules) {
  try {
    if (!fs.existsSync(LIB_DIR)) fs.mkdirSync(LIB_DIR, { recursive: true });
  } catch (e) {
    console.error(`Directory creation failed: ${e.message}`);
  }
  const written = [];
  for (const r of rules) {
    if (r.count < THRESHOLD) continue;
    const template = generateWrapperTemplate(r.rule, r);
    if (!template) continue;
    const file = path.join(LIB_DIR, safeWrapperFilename(r.rule));
    if (DRY_RUN) {
      log(`  [DRY] would write ${file}`);
    } else {
      try {
        fs.writeFileSync(file, template, 'utf8');
      } catch (e) {
        console.error(`File write failed: ${e.message}`);
      }
      written.push(file);
    }
  }
  return written;
}

// ── Main ─────────────────────────────────────────────────────────────────

function main() {
  log(`🔬 observe_audit_patterns.js — Layer 4 v0`);
  log(`   window: ${DAYS} days · threshold: ${THRESHOLD} · generate: ${GENERATE}`);

  const issues = loadAuditHistory(DAYS);
  if (issues.length === 0) {
    log(`   ⚠️  no audit history in .state/audit_history/ (only 1 day available)`);
    log(`   (Layer 3 audit history accumulates daily at 04:30 cron)`);
  }
  log(`   loaded ${issues.length} issues from history`);

  const byRule = aggregateByRule(issues);
  const rules = Object.entries(byRule).map(([rule, info]) => ({ rule, ...info }));
  rules.sort((a, b) => b.count - a.count);

  const dateStr = new Date().toISOString().slice(0, 10);
  const jsonFile = writeJsonReport(rules, dateStr);
  const mdFile = writeMdReport(rules, dateStr);

  log(`   📊 report: ${jsonFile}`);
  log(`   📝 report: ${mdFile}`);

  if (GENERATE) {
    log(`\n🛡️  generating wrapper templates (threshold=${THRESHOLD})...`);
    const written = writeWrapperTemplates(rules);
    if (written.length > 0) {
      log(`   wrote ${written.length} wrapper(s):`);
      for (const f of written) log(`     - ${f}`);
    } else {
      log(`   (no wrapper templates to write for current rules)`);
    }
  } else {
    log(`\n💡 re-run with --generate to write wrapper templates for top patterns`);
  }

  // Summary
  const recurring = rules.filter(r => r.count >= THRESHOLD);
  log(`\n═══════════════════════════════════════`);
  log(`Summary:`);
  log(`   Total issues:      ${rules.reduce((s, r) => s + r.count, 0)}`);
  log(`   Unique rules:      ${rules.length}`);
  log(`   Recurring (≥${THRESHOLD}):  ${recurring.length}`);
  log(`   Top 3: ${rules.slice(0, 3).map(r => r.rule + '(' + r.count + ')').join(', ')}`);
  log(`═══════════════════════════════════════`);

  process.exit(0);
}

main();
