#!/usr/bin/env node

const _quiet = process.argv.includes('--quiet');
const log = (...args) => { if (!_quiet) console.log(...args); };

/**
 * Smart Query Router with Answer Source Display
 * Shows which model provides the final answer and Kimi review status
 */

const { classifyTask } = require('./task_router');

const query = process.argv.slice(2).join(' ');

// Input validation
if (query.length > 2000) {
  console.error('❌ Query too long (max 2000 characters)');
  process.exit(1);
}
if (query.includes('\0')) {
  console.error('❌ Invalid query: contains null bytes');
  process.exit(1);
}

if (!query) {
  log('🤖 Smart Query Router\n');
  log('Usage: node smart_query.js "你的問題"');
  log('\nAnswer Source Types:');
  log('  ┌─────────────────────────────────────────────────┐');
  log('  │ Qwen3 (Direct)      → Local execution           │');
  log('  │ Qwen3 (Kimi Review) → Local + Quality check  ✓  │');
  log('  │ Kimi (Direct)       → Cloud reasoning        ★  │');
  log('  └─────────────────────────────────────────────────┘');
  process.exit(1);
}

// Classify the task
const classification = classifyTask(query);

log('🤖 Smart Query Router\n');
log(`Query: "${query.slice(0, 80)}${query.length > 80 ? '...' : ''}"\n`);

log('📊 Classification:');
log(`  Model: ${classification.model.toUpperCase()}`);
log(`  Confidence: ${(classification.confidence * 100).toFixed(1)}%`);
log(`  Category: ${classification.category}\n`);

// Answer Source Banner
log('╔══════════════════════════════════════════════════════╗');
log('║              📋 ANSWER SOURCE                        ║');
log('╠══════════════════════════════════════════════════════╣');
log(`║  ${classification.answerSource.padEnd(50)}║`);
log('╠══════════════════════════════════════════════════════╣');
log(`║  🔍 Kimi Reviewed: ${classification.kimiReviewed ? 'YES ✓' : 'NO '}                    ║`);
log(`║  ⭐ Quality Level: ${classification.qualityLevel.padEnd(42)}║`);
log('╚══════════════════════════════════════════════════════╝\n');

// Explanation
if (classification.answerSource === 'Qwen3 (Direct)') {
  log('✅ This answer is provided directly by Qwen3');
  log('   → Local processing, standard quality guarantee\n');
} else if (classification.answerSource === 'Qwen3 (Kimi Reviewed)') {
  log('✅ This answer is generated by Qwen3 and reviewed by Kimi');
  log('   → Local processing with quality verification');
  log('   → Financial/critical data double-checked\n');
} else {
  log('★ This answer is provided directly by Kimi');
  log('   → Cloud-based advanced reasoning');
  log('   → Best for complex decisions and strategy\n');
}

// Show relevant scripts for Qwen3 tasks
if (classification.model.includes('qwen3')) {
  const scriptMap = {
    excel: ['scripts/stock_merge_pro.js', 'scripts/vba_generator.js'],
    stock_management: ['scripts/stock_updater.js', 'scripts/stock_merge_pro.js'],
    ocr: ['scripts/tesseract_gia_ocr.js (Tesseract 5.5.2)'],
    automation: [], // removed: referenced scripts no longer exist
    calculation: ['Direct calculation (no script needed)'],
    chart_generation: ['scripts/chart_generator.js'],
    document_generation: ['scripts/quotation_generator.js (Kimi reviewed)'],
    database: ['scripts/gia_database.js']
  };

  const scripts = scriptMap[classification.category];
  if (scripts) {
    log('📁 Relevant scripts:');
    scripts.forEach(s => log(`   • ${s}`));
  }
}

module.exports = { classifyTask };
